### ISSUE TITLE
npm install slp fails

### ISSUE THREAD

**Issue by keithclanton** [tralamazza/node-slp#1]
$ npm install slp

> slp@1.0.2 install /Users/531754/projects/optimus/node_modules/slp
> node-gyp rebuild

  CXX(target) Release/obj.target/slp/src/node_slp.o
In file included from ../src/node_slp.cc:3:
../src/api/baton.h:6:10: fatal error: 'slp.h' file not found
#include <slp.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/slp/src/node_slp.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/531754/projects/optimus/node_modules/slp
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN optimus@0.0.1 No repository field.
npm WARN optimus@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slp@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slp@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/531754/.npm/_logs/2020-02-27T20_30_25_625Z-debug.log

**Comment by tralamazza** [comment]
`fatal error: 'slp.h' file not found`

It's been a while (7y+) for me, but you should have [OpenSLP](http://www.openslp.org/download.html) in your include path
